name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm config set spin false
    - run: npm install -g yarn bower ember-cli@3.28.5
    - run: yarn install
    - run: bower install
    - run: ember build --environment=production
    - uses: actions/upload-artifact@v4
      if: success()
      with:
        name: leosac-web node${{ matrix.node-version }} dist
        path: dist/
#    - run: yarn test
