name: Release
on:
  schedule:
    - cron: '0 4 * * 6' # Every saturday at 4am
  push:
    tags:
      - v*
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      docker_image: ${{ steps.prepare.outputs.docker_image }}
      tag: ${{ steps.prepare.outputs.tag }}
      platforms: ${{ steps.prepare.outputs.platforms }}
    steps:
      - name: Prepare
        id: prepare
        run: |
          DOCKER_IMAGE=leosac/leosac-web
          DOCKER_PLATFORMS=linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          TAG=edge

          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/v}
          fi
          if [ "${{ github.event_name }}" = "schedule" ]; then
            TAG=weekly
          fi
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TAG=snapshot
          fi
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            DOCKER_PLATFORMS=linux/amd64
          fi

          echo ::set-output name=docker_image::${DOCKER_IMAGE}
          echo ::set-output name=platforms::${DOCKER_PLATFORMS}
          echo ::set-output name=tag::${TAG}

  docker:
    runs-on: ubuntu-latest
    needs: [ prepare ]
    steps:
      - name: Prepare
        id: prepare
        run: |
          TAGS="--tag ${{ needs.prepare.outputs.docker_image }}:${{ needs.prepare.outputs.tag }}"
          if [[ ${{ needs.prepare.outputs.tag }} =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            TAGS="$TAGS --tag ${{ needs.prepare.outputs.docker_image }}:latest"
          fi

          echo ::set-output name=buildx_args::--platform ${{ needs.prepare.outputs.platforms }} \
            ${TAGS}
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Docker Login
        if: success()
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Leosac Web Main
        if: success() && github.event_name != 'pull_request'
        run: |
          docker buildx build --push ${{ steps.prepare.outputs.buildx_args }} --file ./Dockerfile
      - name: Inspect image
        if: always() && github.event_name != 'pull_request'
        run: |
          docker buildx imagetools inspect ${{ needs.prepare.outputs.docker_image }}:${{ needs.prepare.outputs.tag }}
